# Generated by Django 5.2.4 on 2025-07-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='질문')),
                ('answer', models.TextField(verbose_name='대답')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='카테고리')),
                ('is_published', models.BooleanField(default=True, verbose_name='공개 여부')),
            ],
            options={
                'verbose_name': '자주하는 질문',
                'verbose_name_plural': '질문 목록',
            },
        ),
    ]
