# Generated by Django 5.2.4 on 2025-07-16 06:13

from django.db import migrations

def create_initial_categories(apps, schema_editor) :
    Category = apps.get_model('question', 'Category')

    categories_to_create = [
        {'name' : '회사', 'order' : '10'},
        {'name' : '제품', 'order' : '20'},
        {'name' : '기술', 'order' : '30'},
        {'name' : '채용', 'order' : '40'},
        {'name' : '기타', 'order' : '50'},
    ]
    
    for category_data in categories_to_create :
        Category.objects.get_or_create(name=category_data['name'], defaults=category_data)
    

def reverse_initial_categories(apps, schema_editor) :
    Category = apps.get_model('question', 'Category')
    categories_to_delete = ['회사','제품','기술','채용','기타']
    for name in categories_to_delete :
        Category.objects.filter(name=name).delete()

    


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_category_alter_faq_category'),
    ]

    operations = [
        migrations.RunPython(create_initial_categories, reverse_initial_categories),
    ]
