# Generated by Django 5.2.4 on 2025-07-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='공고 제목')),
                ('description', models.TextField(verbose_name='공고 내용')),
                ('posted_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '채용공고',
                'verbose_name_plural': '채용공고',
                'ordering': ['-posted_date'],
            },
        ),
    ]
