# Generated by Django 5.2.4 on 2025-07-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruitment_link', models.URLField(blank=True, verbose_name='채용 링크')),
            ],
        ),
    ]
