# Generated by Django 5.2.4 on 2025-07-14 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='공고 제목')),
                ('description', models.TextField(verbose_name='공고 내용')),
                ('image', models.ImageField(blank=True, null=True, upload_to='job_images/', verbose_name='썸네일 이미지')),
                ('link', models.URLField(verbose_name='지원 링크')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
        ),
    ]
