# Generated by Django 5.2.4 on 2025-07-14 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_sitesetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='link',
        ),
        migrations.CreateModel(
            name='JobLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='링크 이름')),
                ('url', models.URLField(verbose_name='링크 주소')),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.jobpost')),
            ],
        ),
    ]
