# Generated by Django 5.2.4 on 2025-07-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_jobpost_link_joblink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='image',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='label',
            field=models.CharField(default='기본링크', max_length=100, verbose_name='링크 이름'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='url',
            field=models.URLField(default='https://naver.com', verbose_name='링크 주소'),
        ),
        migrations.DeleteModel(
            name='JobLink',
        ),
    ]
