# Generated by Django 5.2.4 on 2025-07-15 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_jobpost_image_jobpost_label_jobpost_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='label',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='url',
        ),
    ]
