# Generated by Django 5.2.4 on 2025-07-15 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_jobpost_label_remove_jobpost_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobpost',
            options={'ordering': ['-posted_date']},
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='posted_at',
            new_name='posted_date',
        ),
    ]
