# Generated by Django 5.2.4 on 2025-07-15 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_jobpost_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobpost',
            options={'ordering': ['-posted_date'], 'verbose_name': '채용공고', 'verbose_name_plural': '채용공고'},
        ),
    ]
